// packages/react-mantine/src/components/LanguageUsageCard.tsx
import React, { useState, useEffect } from 'react';
import {
  LanguageUsageProps,
  LanguageStats,
  fetchGitHubData,
  getLanguageUsageStats,
  fetchGenericGitHubAPI,
  getLanguageColor, // Import from core
} from '@github-profile-cards/core';
import { Card, Text, Progress, Group, Title, Stack, Loader, Alert } from '@mantine/core';

export const LanguageUsageCard: React.FC<LanguageUsageProps> = ({ username, token }) => {
  const [languageStats, setLanguageStats] = useState<LanguageStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const loadData = async () => {
      if (!username) return;
      setLoading(true);
      setError(null);
      try {
        const githubData = await fetchGitHubData(username, token);
        if (githubData && githubData.repos) {
          const stats = await getLanguageUsageStats(githubData.repos, fetchGenericGitHubAPI, token);
          setLanguageStats(stats);
        } else {
          setError('User or repository data not found.');
        }
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to load language usage data.');
      } finally {
        setLoading(false);
      }
    };
    loadData();
  }, [username, token]);

  if (loading) {
    return <Loader />;
  }

  if (error) {
    return <Alert color="red" title="Error">{error}</Alert>;
  }

  if (!languageStats || Object.keys(languageStats).length === 0) {
    return (
      <Card shadow="sm" padding="lg" radius="md" withBorder>
        <Title order={4} mb="md">Language Usage</Title>
        <Text>No language data to display.</Text>
      </Card>
    );
  }

  const totalBytes = Object.values(languageStats).reduce((acc, bytes) => acc + bytes, 0);
  if (totalBytes === 0) {
    return (
      <Card shadow="sm" padding="lg" radius="md" withBorder>
        <Title order={4} mb="md">Language Usage</Title>
        <Text>No language byte data to display (total is zero).</Text>
      </Card>
    );
  }

  // Sort languages by usage and take top N or filter by percentage
  const sortedLanguages = Object.entries(languageStats)
    .sort(([, aBytes], [, bBytes]) => bBytes - aBytes)
    .slice(0, 10); // Display top 10 languages, for example

  const progressSections = sortedLanguages.map(([lang, bytes]) => ({
    value: (bytes / totalBytes) * 100,
    color: getLanguageColor(lang) || '#CCCCCC', // Use core's color mapping
    label: lang,
    tooltip: `${lang}: ${((bytes / totalBytes) * 100).toFixed(1)}% (${bytes.toLocaleString()} bytes)`,
  }));

  return (
    <Card shadow="sm" padding="lg" radius="md" withBorder>
      <Title order={4} mb="xl">Language Usage</Title>
      <Progress.Root size="xl" mb="lg">
        {progressSections.map(section => (
          <Progress.Section
            key={section.label}
            value={section.value}
            color={section.color}
            tooltip={section.tooltip}
          />
        ))}
      </Progress.Root>
      <Stack gap="xs">
        {progressSections.map(section => (
          <Group key={section.label} gap="xs">
            <div style={{ width: 10, height: 10, backgroundColor: section.color, borderRadius: '50%' }} />
            <Text size="sm">{section.label} ({section.value.toFixed(1)}%)</Text>
          </Group>
        ))}
      </Stack>
    </Card>
  );
};

// packages/web-components/src/language-usage-card-wc.ts
import {
  fetchGitHubData,
  getLanguageUsageStats,
  fetchGenericGitHubAPI,
  getLanguageColor, // For color consistency
  type LanguageStats,
  type LanguageUsageProps, // { username, token }
} from '@github-profile-cards/core';

class LanguageUsageCardWC extends HTMLElement {
  private shadow: ShadowRoot;
  private _username: string | null = null;
  private _token: string | null = null;

  static get observedAttributes() {
    return ['username', 'token'];
  }

  constructor() {
    super();
    this.shadow = this.attachShadow({ mode: 'open' });
    this.render(); // Initial placeholder
  }

  connectedCallback() {
    this.updateFromAttributes();
    this.fetchAndRenderData();
  }

  attributeChangedCallback(name: string, oldValue: string | null, newValue: string | null) {
    if (oldValue === newValue) return;
    (this as any)[`_${name}`] = newValue;

    if (this.isConnected) {
      this.fetchAndRenderData();
    }
  }

  private updateFromAttributes() {
    this._username = this.getAttribute('username');
    this._token = this.getAttribute('token');
  }

  private async fetchAndRenderData() {
    if (!this._username) {
      this.renderError('Username attribute is required.');
      return;
    }

    this.renderLoading();

    try {
      const githubData = await fetchGitHubData(this._username, this._token || undefined);
      if (!githubData || !githubData.repos) {
        this.renderError('User or repository data not found.');
        return;
      }
      const stats = await getLanguageUsageStats(githubData.repos, fetchGenericGitHubAPI, this._token || undefined);
      this.render(stats);
    } catch (error) {
      this.renderError(error instanceof Error ? error.message : 'Unknown error occurred.');
    }
  }

  private renderError(message: string) {
    this.shadow.innerHTML = `
      <style>:host { display: block; } .error { color: red; border: 1px solid red; padding: 10px; }</style>
      <div class="error">${message}</div>
    `;
  }

  private renderLoading() {
    this.shadow.innerHTML = `
      <style>:host { display: block; } .loading { padding: 10px; }</style>
      <div class="loading">Loading language usage...</div>
    `;
  }

  private render(stats?: LanguageStats) {
    if (!this.shadow) return;

    const styles = `
      :host { display: block; border: 1px solid #ccc; padding: 16px; border-radius: 8px; font-family: sans-serif; }
      h3 { margin: 0 0 12px 0; }
      .lang-item { margin-bottom: 8px; }
      .lang-name { display: inline-block; width: 120px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; vertical-align: middle; }
      .lang-bar-container { display: inline-block; width: calc(100% - 150px); height: 16px; background-color: #f0f0f0; border-radius: 4px; overflow: hidden; vertical-align: middle; }
      .lang-bar { height: 100%; background-color: #0366d6; border-radius: 4px; transition: width 0.3s ease-in-out; }
      .lang-percent { font-size: 0.8em; margin-left: 5px; vertical-align: middle; }
      .error { color: red; }
      .empty { color: #555; }
    `;

    if (!stats || Object.keys(stats).length === 0) {
      this.shadow.innerHTML = `
        <style>${styles}</style>
        <h3>Language Usage</h3>
        <div class="empty">No language data to display.</div>
      `;
      return;
    }

    const totalBytes = Object.values(stats).reduce((acc, bytes) => acc + bytes, 0);
    if (totalBytes === 0) {
        this.shadow.innerHTML = `
        <style>${styles}</style>
        <h3>Language Usage</h3>
        <div class="empty">No language data (0 bytes).</div>
      `;
      return;
    }

    // Sort and take top N, similar to React versions
    const sortedLanguages = Object.entries(stats)
      .sort(([, aBytes], [, bBytes]) => bBytes - aBytes)
      .slice(0, 7); // Top 7 languages

    let content = `<h3>Language Usage</h3>`;
    sortedLanguages.forEach(([lang, bytes]) => {
      const percentage = (bytes / totalBytes) * 100;
      const color = getLanguageColor(lang) || '#0366d6'; // Use core color or a default
      content += `
        <div class="lang-item">
          <span class="lang-name" title="${lang}">${lang}</span>
          <div class="lang-bar-container">
            <div class="lang-bar" style="width: ${percentage.toFixed(1)}%; background-color: ${color};"></div>
          </div>
          <span class="lang-percent">${percentage.toFixed(1)}%</span>
        </div>
      `;
    });

    this.shadow.innerHTML = `<style>${styles}</style>${content}`;
  }
}

customElements.define('language-usage-card-wc', LanguageUsageCardWC);
