// packages/react-mantine/src/components/ProfileCard.tsx
import React, { useEffect, useState } from 'react';
import {
  fetchGitHubData,
  getProfileSummary,
  getGitHubMetrics,
  getTopReposData,
  type GitHubData,
  type ProfileSummaryData,
  type GitHubMetricsData,
  type TopReposData,
  type ProfileCardProps as CoreProfileCardProps, // Renaming to avoid conflict if we define a local variant
} from '@github-profile-cards/core';
import { Card, Avatar, Text, Group, Loader, Alert, SimpleGrid, List, Anchor, Title } from '@mantine/core';
import { IconAlertCircle } from '@tabler/icons-react';

// Re-exporting or re-defining to ensure it's part of this package's API if needed,
// or just use CoreProfileCardProps directly in consuming apps.
export type ProfileCardProps = CoreProfileCardProps;

export const ProfileCard: React.FC<ProfileCardProps> = ({ username, token, variant = 'summary' }) => {
  const [data, setData] = useState<GitHubData | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const loadData = async () => {
      setLoading(true);
      setError(null);
      try {
        const fetchedData = await fetchGitHubData(username, token);
        if (fetchedData) {
          setData(fetchedData);
        } else {
          setError('User not found or an error occurred.');
        }
      } catch (err) {
        setError(err instanceof Error ? err.message : 'An unknown error occurred.');
      } finally {
        setLoading(false);
      }
    };

    if (username) {
      loadData();
    } else {
      setError('GitHub username is required.');
      setLoading(false);
    }
  }, [username, token]);

  if (loading) {
    return (
      <Card shadow="sm" padding="lg" radius="md" withBorder>
        <Group justify="center">
          <Loader />
          <Text>Loading profile...</Text>
        </Group>
      </Card>
    );
  }

  if (error) {
    return (
      <Alert icon={<IconAlertCircle size="1rem" />} title="Error" color="red">
        {error}
      </Alert>
    );
  }

  if (!data) {
    return null; // Or some other placeholder
  }

  if (variant === 'summary') {
    const summary = getProfileSummary(data);
    return (
      <Card shadow="sm" padding="lg" radius="md" withBorder>
        <Group wrap="nowrap">
          <Avatar src={summary.avatar_url} size={94} radius="md" />
          <div>
            <Text fz="lg" fw={500} mt="md">
              {summary.name || summary.login}
            </Text>
            {summary.name && <Text fz="xs" c="dimmed">{summary.login}</Text>}
            <Text fz="xs" c="dimmed" mt={4}>
              {summary.location || 'Location not specified'}
            </Text>
          </div>
        </Group>
        <Text mt="sm" mb="md" c="dimmed" fz="sm">
          {summary.bio || 'No bio available.'}
        </Text>
        <Group justify="space-apart" mt="md">
          <Text fz="sm">Followers: {summary.followers}</Text>
          {/* Add more summary details if needed */}
        </Group>
         <Anchor href={summary.html_url} target="_blank" fz="sm" mt="sm">
          View Profile on GitHub
        </Anchor>
      </Card>
    );
  }

  if (variant === 'metrics') {
    const metrics = getGitHubMetrics(data);
    return (
      <Card shadow="sm" padding="lg" radius="md" withBorder>
        <Title order={4} mb="md">GitHub Metrics</Title>
        <SimpleGrid cols={2}>
          <Text>Public Repos: {metrics.public_repos}</Text>
          <Text>Followers: {metrics.followers}</Text>
          <Text>Following: {metrics.following}</Text>
          <Text>Stars on Top Repos: {metrics.total_stars_on_top_repos}</Text>
        </SimpleGrid>
      </Card>
    );
  }

  if (variant === 'top-repos') {
    const topRepos = getTopReposData(data.repos);
    return (
      <Card shadow="sm" padding="lg" radius="md" withBorder>
         <Title order={4} mb="md">Top Repositories</Title>
        {topRepos.length > 0 ? (
          <List spacing="xs" size="sm">
            {topRepos.map((repo) => (
              <List.Item key={repo.id}>
                <Anchor href={repo.html_url} target="_blank">
                  {repo.name}
                </Anchor>
                {repo.description && <Text size="xs" c="dimmed">{repo.description}</Text>}
                <Group gap="xs">
                    <Text size="xs">Stars: {repo.stargazers_count}</Text>
                    {repo.language && <Text size="xs">Lang: {repo.language}</Text>}
                </Group>
              </List.Item>
            ))}
          </List>
        ) : (
          <Text>No repositories found.</Text>
        )}
      </Card>
    );
  }

  return <Text>Invalid card variant specified.</Text>;
};

// packages/web-components/src/profile-card-wc.ts
import {
  fetchGitHubData,
  getProfileSummary,
  getGitHubMetrics,
  getTopRepos,
  type GitHubData,
  type ProfileSummaryData,
  type GitHubMetricsData,
  type TopReposData,
  // ProfileCardProps from core is { username, token, variant }, which matches attributes
  type ProfileCardProps,
} from '@github-profile-cards/core';

class ProfileCardWC extends HTMLElement {
  private shadow: ShadowRoot;
  private _username: string | null = null;
  private _token: string | null = null;
  private _variant: ProfileCardProps['variant'] = 'summary'; // Default variant

  static get observedAttributes() {
    return ['username', 'token', 'variant'];
  }

  constructor() {
    super();
    this.shadow = this.attachShadow({ mode: 'open' });
    // Initial render or placeholder
    this.render();
  }

  connectedCallback() {
    this.updateFromAttributes();
    this.fetchAndRenderData();
  }

  attributeChangedCallback(name: string, oldValue: string | null, newValue: string | null) {
    if (oldValue === newValue) return;
    (this as any)[`_${name}`] = newValue; // Simplified, assumes attribute name matches private field name convention

    if (name === 'variant') {
        this._variant = newValue as ProfileCardProps['variant'] || 'summary';
    }

    // Re-fetch and render if critical attributes change
    if (this.isConnected) { // Check if the element is in the DOM
        this.fetchAndRenderData();
    }
  }

  private updateFromAttributes() {
    this._username = this.getAttribute('username');
    this._token = this.getAttribute('token');
    this._variant = (this.getAttribute('variant') as ProfileCardProps['variant']) || 'summary';
  }

  private async fetchAndRenderData() {
    if (!this._username) {
      this.renderError('Username attribute is required.');
      return;
    }

    this.renderLoading();

    try {
      const data = await fetchGitHubData(this._username, this._token || undefined);
      if (!data) {
        this.renderError('User not found or error fetching data.');
        return;
      }
      this.render(data);
    } catch (error) {
      this.renderError(error instanceof Error ? error.message : 'Unknown error occurred.');
    }
  }

  private renderError(message: string) {
    this.shadow.innerHTML = `
      <style>
        .error { color: red; border: 1px solid red; padding: 10px; }
      </style>
      <div class="error">${message}</div>
    `;
  }

  private renderLoading() {
    this.shadow.innerHTML = `
      <style>
        .loading { padding: 10px; }
      </style>
      <div class="loading">Loading profile...</div>
    `;
  }

  private render(data?: GitHubData) {
    if (!this.shadow) return;

    // Basic styles - can be expanded significantly
    let styles = `
      :host { display: block; border: 1px solid #ccc; padding: 16px; border-radius: 8px; font-family: sans-serif; }
      .avatar { width: 80px; height: 80px; border-radius: 50%; margin-right: 16px; }
      .container { display: flex; align-items: center; }
      .info h2 { margin: 0 0 4px 0; }
      .info p { margin: 0 0 8px 0; font-size: 0.9em; color: #555; }
      a { color: #0366d6; text-decoration: none; }
      a:hover { text-decoration: underline; }
      ul { list-style: none; padding-left: 0; }
      li { margin-bottom: 8px; border-bottom: 1px solid #eee; padding-bottom: 8px; }
      .error { color: red; }
      .loading { color: #555; }
      .repo-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 16px; }
      .repo-item { border: 1px solid #ddd; padding: 10px; border-radius: 4px; }
      .repo-item h3 { margin: 0 0 5px 0; font-size: 1.1em; }
    `;

    if (!data) {
      this.shadow.innerHTML = `<style>${styles}</style><div class="loading">Initializing...</div>`;
      return;
    }

    let content = '';
    if (this._variant === 'summary') {
      const summary = getProfileSummary(data.user);
      content = `
        <div class="container">
          <img src="${summary.avatar_url}" alt="${summary.login}" class="avatar">
          <div class="info">
            <h2><a href="${summary.html_url}" target="_blank">${summary.name || summary.login}</a></h2>
            ${summary.name && summary.login !== summary.name ? `<p>@${summary.login}</p>` : ''}
            <p>${summary.bio || 'No bio available.'}</p>
            <p>Location: ${summary.location || 'Not specified'}</p>
            <p>Followers: ${summary.followers.toLocaleString()}</p>
          </div>
        </div>
      `;
    } else if (this._variant === 'metrics') {
        const metrics = getGitHubMetrics(data.user, data.repos);
        content = `
            <h2>GitHub Metrics for ${this._username}</h2>
            <p>Public Repos: ${metrics.public_repos.toLocaleString()}</p>
            <p>Followers: ${metrics.followers.toLocaleString()}</p>
            <p>Following: ${metrics.following.toLocaleString()}</p>
            <p>Total Stars (Top Repos): ${metrics.total_stars_on_top_repos.toLocaleString()}</p>
        `;
    } else if (this._variant === 'repos') {
      const topRepos = getTopRepos(data.repos); // This returns { repos: RepoDisplayData[] }
      content = `
        <h2>Top Repositories for ${this._username}</h2>
        <div class="repo-grid">
          ${topRepos.repos.map(repo => `
            <div class="repo-item">
              <h3><a href="${repo.html_url}" target="_blank">${repo.name}</a></h3>
              <p>${repo.description || 'No description.'}</p>
              <p>Stars: ${repo.stargazers_count.toLocaleString()} | Language: ${repo.language || 'N/A'}</p>
            </div>
          `).join('')}
        </div>
      `;
    } else if (this._variant === 'contributions') {
      content = `<p>Contribution data coming soon for ${this._username}.</p>`;
    } else {
      content = `<p class="error">Invalid variant: ${this._variant}</p>`;
    }
    this.shadow.innerHTML = `<style>${styles}</style>${content}`;
  }
}

customElements.define('profile-card-wc', ProfileCardWC);
